import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import { Inter } from "next/font/google";
import { PropsWithChildren } from "react";
import { Box, Theme, ThemePanel } from "@radix-ui/themes";
import NavBar from "@/app/_components/NavBar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Theme appearance="dark" accentColor="teal">
          <Box className="absolute w-full">
            <NavBar />
            {children}
          </Box>
          {/*<ThemePanel />*/}
        </Theme>
      </body>
    </html>
  );
}
